/**
 * The write precondition: one version, one header, one refusal.
 *
 * Every editor-facing write in this app is a read-then-write across two
 * requests — the surface reads bytes, a person edits them for a while, and the
 * route writes what comes back. Nothing in that sequence noticed another actor
 * saving in between, so a draft that outlived someone else's save silently
 * clobbered it. Story 1.7's refresh makes the window WIDER on purpose: it
 * deliberately leaves an open editor alone, so a draft can knowingly be minutes
 * stale.
 *
 * This module owns the whole vocabulary of the guard so no part of it is spelled
 * twice: the version function, the header it travels in, the check the routes
 * run, and the two sentences a refusal shows. It is modelled on
 * `workbench-preview.ts` — pure, client-safe, zero-dependency, executed directly
 * by the node suite — because the version has to be computed identically on the
 * server, in the browser and in the Worker, and a rule living inside a route can
 * only ever be grepped for.
 *
 * WHY A DERIVED VERSION AND NOT A STORAGE ETAG, FOR THE WRITES THIS MODULE
 * VERSIONS. Every write this guards is side-effecting: a page write runs
 * revisions, the index, cross-refs and the activity log; the artifact write runs
 * the log and the `dataVersion` bump. A raw compare-and-set write at the storage
 * layer would bypass all of it. A version DERIVED from the bytes gives the same
 * lost-update detection while leaving the one writer in place.
 *
 * WHAT THIS MODULE NO LONGER VERSIONS: THE SETTINGS STORE (DW-198). A derived
 * version is a value computed over every byte it is shown, and
 * `.llm-wiki-config.json` holds `firecrawlApiKey`, `customApiKey` and
 * `embeddingApiKey`. Serving a hash of that file is serving a function of three
 * secrets on a boundary AD-23 says no secret material crosses — the version
 * moved when a key moved, which is exactly the property a derived version is
 * for and exactly the one AD-23 forbids. The settings guard now uses an OPAQUE
 * TOKEN generated by `saveConfig` and stored beside the config; see `readConfig`
 * and `saveConfig` in `src/lib/config.ts`.
 *
 * WHAT IS LEFT, PRECISELY. {@link contentVersion} over a string is what the page
 * write, the artifact write, the artifact revisions route, the preview route and
 * the editor page all call — the derived scheme is alive and is the whole of it.
 * {@link objectVersion} and {@link stableSerialize} have NO production caller in
 * this repo today: the settings route was the only one, and it no longer
 * derives. They stay exported and are hardened rather than deleted, so the next
 * caller inherits a serializer that does not answer "no change" for two
 * genuinely different values — which is what the settings one silently got.
 *
 * WHAT THIS DOES NOT CLOSE. The check sits immediately before the write, not
 * inside a lock, so two requests in flight at the same instant can still
 * interleave. That residual is pre-existing and distinct; this closes the window
 * an OPEN EDITOR creates, which is the one measured in minutes.
 */

// ---------------------------------------------------------------------------
// The version
// ---------------------------------------------------------------------------

/**
 * The 32-bit FNV-1a prime, as `Math.imul` wants it.
 *
 * `Math.imul` rather than `*` because the product of two 32-bit values exceeds
 * `Number.MAX_SAFE_INTEGER` and plain multiplication silently loses the low
 * bits — which is a hash that stops distinguishing the inputs it exists to
 * distinguish.
 */
const FNV_PRIME = 0x01000193;

/**
 * The SECOND pass's multiplier, and the reason the two passes are worth running.
 *
 * Two FNV-1a passes that share a prime and differ only in their starting state
 * are not independent: the same multiply-chain acts on both, so the second pass
 * adds real but distinctly sub-32 additional bits rather than doubling them.
 * Giving the second pass its own odd multiplier — odd so the multiplication
 * stays invertible mod 2^32 — makes the two chains genuinely different
 * functions of the same bytes, at the same cost.
 */
const MIX_PRIME = 0x85ebca6b;

/**
 * Two DIFFERENT passes over the same bytes.
 *
 * One 32-bit pass collides at roughly one pair in four billion, which is more
 * than a change detector needs but not more than a long-lived editor deserves.
 * Two passes with different bases AND different multipliers, concatenated,
 * give a wide combined value at the cost of one extra loop over a string
 * already in memory. This is a change detector, not a digest, so the claim is
 * "wide enough that a real edit is never mistaken for no edit", not a bit count
 * anyone should rely on. The first basis is FNV-1a's published one; the second
 * is deliberately unrelated to it.
 */
const OFFSET_BASIS_A = 0x811c9dc5;
const OFFSET_BASIS_B = 0x1b873593;

/**
 * One FNV-1a pass over BOTH BYTES of every UTF-16 code unit.
 *
 * `charCodeAt` is what JavaScript can read without allocating; hashing only its
 * low byte would make `"a"` and `"ā"` (U+0101) the same version, which is a
 * lost-update detector that cannot see a diacritic being added. Feeding the low
 * byte and then the high byte separately keeps the mixing per-byte, as FNV
 * specifies, and needs no encoder — so this is byte-identical in node, in the
 * browser and in the Worker.
 *
 * Lone surrogates are hashed as themselves rather than being repaired. This
 * function is not an encoder: a string holding half a pair is a string the
 * storage layer will store, and the version has to describe what is actually
 * there.
 */
function fnv1a32(input: string, basis: number, prime: number): number {
  let hash = basis >>> 0;
  for (let index = 0; index < input.length; index += 1) {
    const unit = input.charCodeAt(index);
    hash = Math.imul(hash ^ (unit & 0xff), prime);
    hash = Math.imul(hash ^ (unit >>> 8), prime);
  }
  return hash >>> 0;
}

/** Zero-padded so the two passes concatenate at a fixed width. */
function hex32(value: number): string {
  return value.toString(16).padStart(8, "0");
}

/**
 * The version of a string of bytes.
 *
 * A CHANGE DETECTOR, NOT A DIGEST. It is not a cryptographic hash, not an
 * identity, and not a secret: anyone who can read the bytes can compute it, and
 * anyone who wants a collision can construct one. The only question it answers
 * is "are these the same bytes the editor was seeded from", and the only
 * consequence of a wrong answer is a save that should have been refused, or a
 * refusal the owner recovers from by reloading. Nothing is authorized by it.
 *
 * The LENGTH is part of the string, not just of the hash state: it is free, it
 * is the single most discriminating cheap property of an edit, and it makes a
 * version legible in a log line.
 *
 * `w1:` names the scheme so a stored or in-flight version from a future scheme
 * can never be mistaken for a match.
 */
export function contentVersion(content: string): string {
  const length = content.length.toString(36);
  return `w1:${length}-${hex32(
    fnv1a32(content, OFFSET_BASIS_A, FNV_PRIME),
  )}${hex32(fnv1a32(content, OFFSET_BASIS_B, MIX_PRIME))}`;
}

/**
 * How deep a value may nest before {@link stableSerialize} gives up.
 *
 * A BOUND, NOT A LIMIT ANYONE SHOULD MEET. Parsed JSON that nests a hundred
 * deep is a payload nobody typed, and the alternative to refusing it is a stack
 * overflow — a `RangeError` thrown from a name, with a sentence, is the same
 * outcome a caller can catch and attribute. `JSON.stringify` behaves the same
 * way for the same reason; this one simply names the depth instead of
 * discovering it from the engine's stack.
 */
const MAX_SERIALIZE_DEPTH = 100;

/**
 * The name a non-plain object is serialized under.
 *
 * Empty for a plain object and for a null-prototype one, so `{}` keeps
 * serializing as `{}`. Otherwise the constructor's name, which is what
 * separates `new Point(1,2)` from `{ x: 1, y: 2 }` — the built-in `[object Tag]`
 * cannot, because every class instance shares the `Object` tag. The `[object …]`
 * form is the fallback for the objects that have no usable constructor name.
 */
function tagOf(value: object): string {
  const proto: unknown = Object.getPrototypeOf(value);
  if (proto === Object.prototype || proto === null) return "";
  const name = (proto as { constructor?: { name?: unknown } }).constructor?.name;
  if (typeof name === "string" && name.length > 0) return name;
  return Object.prototype.toString.call(value).slice(8, -1);
}

/**
 * Serialize a value so two objects with the same VALUES hash the same however
 * their keys happen to be ordered.
 *
 * `JSON.stringify` preserves insertion order, and the files this versions are
 * hand-editable and re-serialized on save — so a document re-ordered by a text
 * editor, or by one `{ ...existing }` spread landing its keys differently, would
 * read as a change nobody made and refuse a save that conflicts with nothing.
 *
 * `undefined` members are dropped rather than rendered, exactly as
 * `JSON.stringify` drops them, so `{ a: 1 }` and `{ a: 1, b: undefined }` — the
 * two shapes a `delete updated.b` and a `b: undefined` produce — agree. Arrays
 * keep their order: an array's order IS its value.
 *
 * TOTAL OVER VALUES, EXCEPT THE TWO THAT CANNOT BE ANSWERED (DW-197). A cycle
 * has no serialization, and a value nested past {@link MAX_SERIALIZE_DEPTH} has
 * none this can produce without overflowing the stack; both THROW, named and
 * catchable, exactly as `JSON.stringify` throws on a cycle. Everything else
 * gets a value that actually distinguishes it: `Date`, `Map`, `Set`, `RegExp`
 * and class instances used to collapse to `{}` — `Object.entries` sees no own
 * enumerable keys on any of them — so two different dates, or two maps with
 * different contents, produced the SAME version and a real edit read as no
 * edit. `toJSON` is honoured where a value defines one (that is the contract
 * `JSON.stringify` established, and it is how `Date` says what it is), with the
 * type name kept alongside so a `Date` and its own ISO string are not confused.
 */
function serialize(value: unknown, seen: Set<object>, depth: number): string {
  if (depth > MAX_SERIALIZE_DEPTH) {
    throw new RangeError(
      `Value nests deeper than ${MAX_SERIALIZE_DEPTH} levels and cannot be versioned`,
    );
  }
  if (value === null || typeof value !== "object") {
    // `bigint` is the one primitive `JSON.stringify` THROWS on rather than
    // dropping; this is a change detector and a thrown version would take a
    // route down, so it is rendered by value instead.
    if (typeof value === "bigint") return `bigint(${value.toString()})`;
    // `undefined`, functions and symbols stringify to `undefined`; they are not
    // JSON, and rendering them as `null` keeps this total.
    return JSON.stringify(value) ?? "null";
  }

  const object = value as object;
  // ANCESTORS, not "everything visited": a value referenced twice from
  // different branches is a DAG, which serializes fine and is common in parsed
  // config. Only a value that contains itself is a cycle.
  if (seen.has(object)) {
    throw new TypeError("Converting circular structure to a version");
  }
  seen.add(object);
  try {
    const next = (member: unknown) => serialize(member, seen, depth + 1);
    const tag = tagOf(object);

    /**
     * A built-in collection, named by its KIND and by its class when those
     * differ.
     *
     * Both halves matter, and each closes a collision the other leaves open.
     * Without the class, `class MyMap extends Map` serialized identically to a
     * plain `Map` holding the same entries. Without the KIND — and without the
     * `<…>` delimiter, which the object and `toJSON` paths (`{…}` and `(…)`)
     * can never produce — a user class merely NAMED `Set`, holding no own
     * fields, serialized identically to an empty real `Set`. Two different
     * values, one version, is exactly what this serializer was hardened to
     * stop.
     */
    const collection = (kind: string, body: string) =>
      tag === kind ? `${kind}<${body}>` : `${tag}(${kind}<${body}>)`;

    if (Array.isArray(object)) {
      const members = `[${object.map(next).join(",")}]`;
      return tag === "Array" ? members : `${tag}(${members})`;
    }
    if (object instanceof Map) {
      // Sorted by SERIALIZED entry, so two maps built in different insertion
      // orders agree — the same reason object keys are sorted.
      const entries = Array.from(object.entries())
        .map(([key, member]) => `${next(key)}=>${next(member)}`)
        .sort();
      return collection("Map", entries.join(","));
    }
    if (object instanceof Set) {
      const members = Array.from(object.values()).map(next).sort();
      return collection("Set", members.join(","));
    }
    if (object instanceof RegExp) {
      // Its own branch because a `RegExp` has no own enumerable keys AND no
      // `toJSON`: `/a/` and `/b/` would otherwise both be `RegExp{}`.
      return collection("RegExp", object.toString());
    }

    const toJSON = (object as { toJSON?: unknown }).toJSON;
    if (typeof toJSON === "function") {
      const replaced = (toJSON as (key?: string) => unknown).call(object);
      return `${tag}(${next(replaced)})`;
    }

    const entries = Object.entries(object as Record<string, unknown>)
      .filter(([, member]) => member !== undefined)
      .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0));
    const body = `{${entries
      .map(([key, member]) => `${JSON.stringify(key)}:${next(member)}`)
      .join(",")}}`;
    return tag === "" ? body : `${tag}${body}`;
  } finally {
    // Leaving the branch un-marks it, which is what makes `seen` an ancestor
    // path rather than a visited set.
    seen.delete(object);
  }
}

/**
 * The stable, key-order-independent serialization {@link objectVersion} hashes.
 *
 * Exported for the suite and for any caller that wants the string rather than
 * the version. Throws `TypeError` on a cycle and `RangeError` past
 * {@link MAX_SERIALIZE_DEPTH}; see {@link serialize} for everything else.
 */
export function stableSerialize(value: unknown): string {
  return serialize(value, new Set<object>(), 0);
}

/**
 * The version of a parsed object — key-order independent, nested and all.
 *
 * A GENERAL PRIMITIVE, AND EXPLICITLY NOT THE SETTINGS SCHEME. It compares a
 * parsed object rather than a byte string, which is what a caller wants when the
 * file it guards is rewritten by its own serializer. It is NOT what
 * `/api/settings` uses: that store holds three API keys, and a version derived
 * from a store is a function of everything in it — see the module docblock,
 * `readConfig` and `saveConfig` in `src/lib/config.ts`.
 *
 * Inherits {@link stableSerialize}'s two throws. Both are catchable and both
 * mean the same thing to a caller: this value has no version, so do not pretend
 * it matches one.
 */
export function objectVersion(value: unknown): string {
  return contentVersion(stableSerialize(value));
}

// ---------------------------------------------------------------------------
// The header
// ---------------------------------------------------------------------------

/**
 * The precondition travels in the standard header, spelled once.
 *
 * `If-Match` rather than a body field: a precondition is about the request, not
 * about the content, so it does not have to survive every body shape a route
 * accepts — a `PATCH`-style partial patch, a whole-object `PUT` and a
 * `{ content }` envelope all carry it the same way, and no route has to reserve
 * a key name inside a payload it also validates.
 *
 * It is NOT checked before the body is parsed. Each route checks at its own
 * merge base — after the read whose bytes it compares against, and after the
 * refusals that must not leak whether a target exists (the page route's ACL
 * cloak). One visible consequence: a stale save that ALSO carries an invalid
 * field is answered 400 for the field, not 412 for the conflict, and meets the
 * conflict only once the field is fixed. That ordering is deliberate — a
 * request that would be refused anyway should not learn a version — but it does
 * mean the refusals are not strictly prioritized by this header.
 */
export const IF_MATCH_HEADER = "If-Match";

/** Wrap a version as the strong validator `If-Match` is defined to carry. */
export function formatIfMatch(version: string): string {
  return `"${version}"`;
}

/**
 * Read a version out of an `If-Match` header, or `null` when there is none.
 *
 * ANYTHING THAT IS NOT ONE QUOTED VALUE IS ABSENT. `*` is the wildcard that
 * means "any current representation", which is precisely the unconditional write
 * this guard exists to stop — accepting it would let a caller opt out of the
 * precondition by sending one character. An unquoted value, an empty string, a
 * list, and a weak validator are all refused for the same reason: a guard a
 * caller can skip by malforming a header is not a guard, and every client in
 * this repo sends exactly what {@link formatIfMatch} produces.
 */
export function parseIfMatch(header: string | null | undefined): string | null {
  if (typeof header !== "string") return null;
  const trimmed = header.trim();
  const matched = /^"([^"]+)"$/.exec(trimmed);
  return matched ? matched[1] : null;
}

// ---------------------------------------------------------------------------
// Copy — ONE wording for the conflict, owned here
// ---------------------------------------------------------------------------

/**
 * What a refused-because-stale save says, on every surface.
 *
 * RECOVERABLE, and it says so: the draft is still on screen, nothing was
 * destroyed, and the way out is a reload. It never names a file, a person or a
 * time — the route knows none of them, and a sentence that guessed would be
 * wrong on the Settings surface where "another actor" is usually the owner's own
 * second tab.
 *
 * One string, in one module, relayed as the routes' existing `{ error }` — the
 * contract all four clients already show verbatim. No surface types a conflict
 * sentence at its render site.
 */
export const WRITE_CONFLICT_COPY =
  "This was changed somewhere else while you were editing, so your save was not applied. Your text is still here — copy it, reload, and apply it to the current version.";

/**
 * What a save with no usable precondition says.
 *
 * Its own sentence rather than the conflict one, because it is a different
 * fact: nothing is known to have changed, the request simply could not be
 * checked. Reaching it means a client sent a `PUT` without the version it was
 * seeded with, which is a bug rather than a race.
 *
 * The RECOVERY half is word-for-word the conflict's, deliberately: reloading
 * destroys the draft identically in both cases, so "copy it" is exactly as
 * load-bearing here. Only the first clause — what happened — differs.
 */
export const WRITE_PRECONDITION_REQUIRED_COPY =
  "This save could not be checked against the stored version, so it was not applied. Your text is still here — copy it, reload, and apply it to the current version.";

// ---------------------------------------------------------------------------
// The check
// ---------------------------------------------------------------------------

/** No `If-Match` at all, or one nothing could be read out of. */
export const WRITE_PRECONDITION_REQUIRED_STATUS = 428;

/** An `If-Match` that does not describe the bytes the route is holding. */
export const WRITE_CONFLICT_STATUS = 412;

export type PreconditionOutcome =
  | { ok: true }
  | {
      ok: false;
      status: typeof WRITE_PRECONDITION_REQUIRED_STATUS;
      error: typeof WRITE_PRECONDITION_REQUIRED_COPY;
    }
  | {
      ok: false;
      status: typeof WRITE_CONFLICT_STATUS;
      error: typeof WRITE_CONFLICT_COPY;
    };

/**
 * May this write proceed?
 *
 * `current` is the version of the bytes the route ALREADY READ for its own merge
 * — never a second read taken for this check, which would be a different moment
 * and a different answer. `null` means the target is GONE, and a missing target
 * matches no version: a save into a hole is exactly the lost update this
 * refuses, and answering 412 keeps the draft.
 *
 * Three outcomes and no fourth. There is deliberately no "skip the check when
 * the header is absent" branch: that is the unconditional write, and a guard a
 * caller opts out of by omitting a header is not a guard.
 */
export function checkWritePrecondition(
  header: string | null | undefined,
  current: string | null,
): PreconditionOutcome {
  const supplied = parseIfMatch(header);
  if (supplied === null) {
    return {
      ok: false,
      status: WRITE_PRECONDITION_REQUIRED_STATUS,
      error: WRITE_PRECONDITION_REQUIRED_COPY,
    };
  }
  if (current === null || supplied !== current) {
    return {
      ok: false,
      status: WRITE_CONFLICT_STATUS,
      error: WRITE_CONFLICT_COPY,
    };
  }
  return { ok: true };
}
