import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import {
  BULK_DELETE_READ_ONLY_COPY,
  RecentIngests,
} from "@/components/RecentIngests";

/**
 * The recent-ingests bulk delete on a read-only deployment, MOUNTED (DW-265).
 *
 * `DELETE /api/ingest/history` has refused since DW-187, and the control in
 * front of it kept opening a `window.confirm` promising that "Generated wiki
 * pages and their derived indexes will be permanently removed" — an
 * irreversible-sounding dialog answered onto a 403. `/ingest` is `"use client"`
 * from the page down, so the fact cannot arrive as a prop; it rides on the GET
 * this list already makes.
 *
 * Every assertion is on the outermost surface: what is on screen, whether
 * `window.confirm` was ever raised, and what requests were issued.
 */

vi.mock("@/hooks/useSlugTenants", () => ({
  useSlugTenants: () => ({ hrefForSlug: (slug: string) => `/u/yopedia/${slug}` }),
}));
vi.mock("@/lib/recent-ingests", () => ({
  getRecentJobIds: () => [],
  forgetRecentJobs: vi.fn(),
}));

const ENTRY = {
  ingest_id: "ing-1",
  source_url: "https://example.com/article",
  primary_slug: "article",
  finished_at: "2026-08-20T12:00:00.000Z",
  status: "completed",
  source_type: "url",
};

let fetchMock: ReturnType<typeof vi.fn>;
let confirmMock: ReturnType<typeof vi.fn>;

/**
 * Answer every endpoint this component polls on mount, with the history GET
 * carrying `readOnly` as the route now serves it.
 */
function stubFetch(readOnly: boolean | undefined) {
  fetchMock = vi.fn(async (url: unknown) => {
    const href = String(url);
    const body = href.startsWith("/api/ingest/history")
      ? { entries: [ENTRY], ...(readOnly === undefined ? {} : { readOnly }) }
      : { jobs: [] };
    return { ok: true, status: 200, json: async () => body } as unknown as Response;
  });
  vi.stubGlobal("fetch", fetchMock);
}

/**
 * The same stub with an EMPTY ledger — a read-only deployment with nothing
 * deletable, where no control exists for the sentence to describe.
 */
function stubFetchEmpty(readOnly: boolean) {
  fetchMock = vi.fn(async (url: unknown) => {
    const href = String(url);
    const body = href.startsWith("/api/ingest/history")
      ? { entries: [], readOnly }
      : { jobs: [] };
    return { ok: true, status: 200, json: async () => body } as unknown as Response;
  });
  vi.stubGlobal("fetch", fetchMock);
}

/** The DELETE requests this component issued, if any. */
function deleteCalls(): unknown[][] {
  return fetchMock.mock.calls.filter(
    (call) => (call[1] as RequestInit | undefined)?.method === "DELETE",
  );
}

function bulkDelete(): HTMLButtonElement {
  return screen.getByRole("button", { name: "Bulk delete" }) as HTMLButtonElement;
}

beforeEach(() => {
  // Defaults to ACCEPTING, so a missing gate shows up as a DELETE request
  // rather than as a dialog nobody answered.
  confirmMock = vi.fn(() => true);
  vi.stubGlobal("confirm", confirmMock);
});

afterEach(() => {
  // FIRST: vitest runs afterEach hooks in reverse registration order, so the
  // setup file's `cleanup()` lands after this one and would unmount with the
  // globals still stubbed.
  cleanup();
  vi.unstubAllGlobals();
});

describe("the bulk delete refuses on a read-only deployment", () => {
  it("states the refusal, opens no confirm and sends no DELETE", async () => {
    stubFetch(true);
    render(<RecentIngests />);

    await screen.findByText(BULK_DELETE_READ_ONLY_COPY);


    fireEvent.click(bulkDelete());

    // The refusal lands BEFORE selection mode, so there is nothing to select
    // and no "Delete selected" to press — which is what keeps the confirm out
    // of reach entirely.
    expect(confirmMock).not.toHaveBeenCalled();
    expect(deleteCalls()).toEqual([]);
    expect(screen.queryByRole("button", { name: /Delete selected/ })).toBeNull();
  });

  it("describes the control with the sentence, and keeps it reachable", async () => {
    stubFetch(true);
    render(<RecentIngests />);

    await screen.findByText(BULK_DELETE_READ_ONLY_COPY);
    const button = bulkDelete();

    // `aria-disabled`, never `disabled`: the control keeps its place in the tab
    // order so the sentence can be announced with it.
    expect(button.getAttribute("aria-disabled")).toBe("true");
    expect(button.hasAttribute("disabled")).toBe(false);

    // Read OFF the control rather than restated here: the id is generated by
    // `useId()`, and a test that named it would be pinning a literal the
    // component is free to stop using.
    const noteId = button.getAttribute("aria-describedby");
    expect(noteId).toBeTruthy();
    const note = document.getElementById(noteId!);
    expect(note).not.toBeNull();
    expect(note!.textContent).toBe(BULK_DELETE_READ_ONLY_COPY);
  });

  it("says nothing when there is no control for the sentence to describe", async () => {
    // A read-only deployment whose list holds nothing deletable renders no Bulk
    // delete button at all, so a sentence here would announce the refusal of an
    // operation the owner was never offered, pointing at nothing.
    stubFetchEmpty(true);
    render(<RecentIngests />);

    await waitFor(() => expect(fetchMock).toHaveBeenCalled());
    await waitFor(() =>
      expect(screen.queryByText(BULK_DELETE_READ_ONLY_COPY)).toBeNull(),
    );
    expect(screen.queryByRole("button", { name: "Bulk delete" })).toBeNull();
  });

  it("says nothing and opens selection mode on a writable deployment", async () => {
    // The control case. Without it every assertion above would also pass
    // against a list whose Bulk delete had simply stopped working.
    stubFetch(false);
    render(<RecentIngests />);

    await screen.findByRole("button", { name: "Bulk delete" });
    expect(screen.queryByText(BULK_DELETE_READ_ONLY_COPY)).toBeNull();
    expect(bulkDelete().hasAttribute("aria-disabled")).toBe(false);

    fireEvent.click(bulkDelete());

    expect(screen.getByRole("button", { name: /Delete selected/ })).toBeTruthy();
  });

  it("stays live when the route serves no readOnly field at all", async () => {
    // A route that stopped sending the field must leave the list working rather
    // than refusing everything on an `undefined` — the server refuses either
    // way, and a refusal invented on the client would be the worse failure.
    stubFetch(undefined);
    render(<RecentIngests />);

    await screen.findByRole("button", { name: "Bulk delete" });
    await waitFor(() =>
      expect(screen.queryByText(BULK_DELETE_READ_ONLY_COPY)).toBeNull(),
    );
    expect(bulkDelete().hasAttribute("aria-disabled")).toBe(false);
  });
});
